# Generated by Django 3.2.12 on 2022-06-27 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_notedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.EmailField(max_length=100)),
                ('abstract', models.CharField(max_length=132)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
                ('username', models.EmailField(max_length=100)),
                ('content', models.CharField(max_length=1200)),
            ],
            options={
                'db_table': 'ArticleData',
            },
        ),
        migrations.AlterField(
            model_name='notedata',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
