# Generated by Django 3.2.12 on 2022-06-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_auto_20220627_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledata',
            name='article_id',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
