# Generated by Django 3.2.12 on 2022-07-06 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_auto_20220701_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('result', models.CharField(max_length=150)),
                ('type', models.IntegerField()),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('username', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'ExpData',
            },
        ),
    ]
